### ISSUE TITLE
Would this work for self-hosted Parse Server?

### ISSUE THREAD

**Issue by jeffreyjackson** [a2/passcards-parse#1]

**Comment by a2** [comment]
It will work, yes, but it'll require some tweaking and massaging to make it work correctly. Better to use the [_passcards-swift_](https://github.com/a2/passcards-swift) library.

**Comment by jeffreyjackson** [comment]
Thanks, looking for a parse solution however since our backend is already using parse.  would be nice to have all of the objects in one place.
